[package]
name = "dataset_builder"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
clap = { version = "4.0", features = ["derive", "env"] }
csv = "1.3"
git2 = "0.18"
ignore = "0.4"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
